name: openghg_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python >= 3.8
  - addict
  - dask
  - h5netcdf
  - matplotlib
  - msgpack-python
  - nbformat
  - numexpr
  - numpy
  - nc-time-axis
  - pandas
  - plotly
  - pyvis
  - rapidfuzz
  - requests >= 2.25
  - scipy
  - tinydb
  - toml
  - tqdm
  - xarray = v2022.09.0
  - urllib3 >= 1.26.3
  - pip
  - xesmf
  - pip:
    - icoscp
