name: openghg_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python >= 3.8
  - addict
  - dask
  - h5netcdf
  - matplotlib
  - msgpack-python
  - netcdf4
  - nbformat
  - numexpr
  - numpy
  - nc-time-axis
  - pandas < 2.0
  - plotly
  - pyvis
  - rapidfuzz
  - requests >= 2.25
  - rich
  - scipy
  - tinydb
  - toml
  - xarray
  - urllib3 >= 1.26.3
  - pip
  - xesmf >= 0.7
  - pip:
    - icoscp
    - openghg_defs @ git+https://github.com/openghg/supplementary_data
